############################################################
#
# 配置项目信息
#
############################################################
server:
  port: ${port:7070}
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: zuul
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: PT1H
  redis:
    # redis数据库索引(默认为0)
    database: 0
    # redis服务器IP地址
    host: 127.0.0.1
    # redis端口号
    port: 6379
    # redis密码，默认为空
    password: sl6819961
    # 连接redis超时时间（毫秒）
    timeout: PT2S
    #jedis连接池
    jedis:
      pool:
        # 最大等待时间
        max-wait: 1000
        # 最小空闲数量
        min-idle: 1
        # 最大空闲数量
        max-idle: 10
        # 最大连接数量
        max-active: 1000
############################################################
#
# eureka client 配置信息
#
############################################################
eureka:
  # 自定义eureka server的信息
  server:
    hostname: eureka
    port: 7000
  client:
    # 所有的微服务都必须注册到eureka中
    register-with-eureka: true
    # 从注册中心获得检索服务实例
    fetch-registry: true
    # 注册中心的服务地址
    service-url:
      #defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      defaultZone: http://eureka-cluster-7001:7001/eureka/,http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/
  instance:
    # 调整微服务（eureka client）和注册中心（eureka server）的心跳时间
    lease-renewal-interval-in-seconds: 3
    # eureka 举例最近的一次心跳等待提出的时间，默认90s
    lease-expiration-duration-in-seconds: 5
zuul:
  # 请求前缀
  prefix: /api
  routes:
    # 由于路由id和微服务实例id相同，我们可以简化转发的配置
    #    banner-service: /banner-service/**
    # 配置微服务的路由id，微服务的实例id
    service-article:
      # 请求路径(前缀)
      # 请求转发的微服务实例id
      path: /banner-service/**
      # service-id: banner-service
      # 请求转发到指定的微服务所在的ip地址 service-id可替换为url
      url: http://192.168.0.3:8001
# 通过redis自定义限流规则
blackIp:
  continueCounts: ${counts:10} # ip连续点击次数
  timeInterval: ${interval:10} # ip连续点击限制时间 单位：秒
  limitTimes: ${times:15} # ip限制访问时间 单位：秒